//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.05 at 06:47:35 PM CEST 
//


package com.itakademija.jaxb;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Country complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Country"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Country_Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Country_Capital" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Country_Foundation_Date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Country_Continent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Country_Population" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Country", propOrder = {
    "countryName",
    "countryCapital",
    "countryFoundationDate",
    "countryContinent",
    "countryPopulation"
})
public class Country {

    @XmlElement(name = "Country_Name", required = true)
    protected String countryName;
    @XmlElement(name = "Country_Capital", required = true)
    protected String countryCapital;
    @XmlElement(name = "Country_Foundation_Date", required = true)
    protected String countryFoundationDate;
    @XmlElement(name = "Country_Continent", required = true)
    protected String countryContinent;
    @XmlElement(name = "Country_Population", required = true)
    protected BigInteger countryPopulation;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the countryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the countryCapital property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCapital() {
        return countryCapital;
    }

    /**
     * Sets the value of the countryCapital property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCapital(String value) {
        this.countryCapital = value;
    }

    /**
     * Gets the value of the countryFoundationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryFoundationDate() {
        return countryFoundationDate;
    }

    /**
     * Sets the value of the countryFoundationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryFoundationDate(String value) {
        this.countryFoundationDate = value;
    }

    /**
     * Gets the value of the countryContinent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryContinent() {
        return countryContinent;
    }

    /**
     * Sets the value of the countryContinent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryContinent(String value) {
        this.countryContinent = value;
    }

    /**
     * Gets the value of the countryPopulation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCountryPopulation() {
        return countryPopulation;
    }

    /**
     * Sets the value of the countryPopulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCountryPopulation(BigInteger value) {
        this.countryPopulation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
